### ISSUE TITLE
HandleNoteOn / HandleNoteOff / HandleParameterChange does not get called or is inconsistent

### ISSUE THREAD

**Issue by randomcmd** [mikeoliphant/AudioPlugSharp#27] opened 2024-03-16 20:50 UTC
Hi love your work!
I just tried making a small plugin for 10 hours, but even the example plugin does not work correctly? The functions above will not get called. Only HandleParameterChange will get called once per startup per plugin instance, but for some reason I can not get these functions to behave correctly. I have tried a lot of debugging, but I think this might not be a fault with my code? I am using FLStudio 21. I am very grateful for your work I think it's awesome to see C# for VST!

**Comment by mikeoliphant** [comment] 2024-03-16 22:32
A few things to check:

Are you calling Host.ProcessAllEvents() or looping using Host.ProcessEvents() in your Process() method?

Are you sure that you are routing MIDI events properly to the plugin from the DAW?

**Comment by randomcmd** [comment] 2024-03-17 21:25
I am using Host.ProcessEvents() like in the example and it's throwing a NullPointerException in that function. Also while messing around with the MIDI events I found out the plugin calls the function only if I reload the plugin, but it calls it twice, which is funny because clicking the key is supposed to toggle my light so it just stays.

**Comment by mikeoliphant** [comment] 2024-03-17 21:55
I've just tested the MidiExample plugin to make sure there haven't been any regressions, and it is working fine for me. I don't use FLStudio, though.

Can you verify whether or not the MidiExample plugin is working for you? It should play a tone corresponding to incoming midi note values.

**Comment by randomcmd** [comment] 2024-03-17 22:50
Does not play any notes!

**Comment by mikeoliphant** [comment] 2024-03-18 00:20
I grabbed FL Studio, and there is indeed a problem there.

MIDI is working fine, but audio output isn't . FL Studio seems to force 32bit audio processing, and I must have broken 32bit support at some point. I'll look into it.

**Comment by randomcmd** [comment] 2024-03-18 01:12
I fixed all my issues by not having two instasnces of my plugin at the same time. The only small bug I encountered is (unrelated to this that's it's own issue) that if I create a Parameter that starts at a value like 50 it makes the plugin not load. 

Thanks a lot for taking your time with this (:

**Comment by mikeoliphant** [comment] 2024-03-18 17:40
I have fixed the issues with audio output on FL Studio. The MidiExample plugin now works fine for me there.

There should not be problems running multiple instances of a plugin. Do be aware, though, that if you are using WPF then all plugins are run in the same assembly space - that means that any static variables will be shared between them.

**Comment by mikeoliphant** [comment] 2024-03-21 00:17
I'm going to close this, since I've fixed the issue I was able to reproduce. Feel free to open a new issue if you still have any problems.

**Closed as completed by mikeoliphant** 2024-03-21 00:17 UTC
